version: '2'
services:
  web:
    build: .
    container_name: docker-web
    volumes:
      - ./../:/var/www/html
    ports:
      - "80:80"
      - "8890:8890"
    extra_hosts:
      - "apilobe.local:127.0.0.1"
    links:
      - redis
      - serverdb
  serverdb:
    image: mysql:5.7
    container_name: docker-db
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=admin
    ports:
      - 3406:3306
  redis:
    image: redis
    container_name: docker-redis
    volumes:
      - ./data/redis:/data
    ports:
      - "6380:6379"
